version: '3'
services: 
    bot:
        build: .
        ports:
            - "22:22"
        volumes:
            - .:/bot
        environment:
            - BOT_TOKEN
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: linnanvahti
            POSTGRES_DB: ovivahtidb
    dbadmin:
        image: adminer
        restart: always
        volumes:
            - /dbInitScripts:/docker-entrypoint-initdb.d/
        ports:
            - 8080:8080
