version: '3'
services: 
    bot:
        build: .
        ports:
            - "22:22"
        volumes:
            - .:/bot
        environment:
            - BOT_TOKEN
    db:
        image: postgres
        restart: always
        volumes:
            - ./dbInitScripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: linnanvahti
            POSTGRED_DB: ovivahtidatabase
    dbadmin:
        image: adminer
        restart: always
        ports:
            - 8080:8080
