version: '3'
services: 
    bot:
        build: 
            context: .
            dockerfile: bot/Dockerfile
        restart: always
        ports:
            - "22:22"
        volumes:
            - ./bot:/bot
        environment:
            - BOT_TOKEN
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_HOST
        depends_on: 
            - "db"
        command: ["./wait-for-postgres.sh", "db", "python3", "bot.py"]
    adminbot:
        build: 
            context: .
            dockerfile: adminbot/Dockerfile
        restart: always
        ports:
            - "23:22"
        volumes:
            - ./adminbot:/adminbot
        environment:
            - ADMINBOT_TOKEN
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_HOST
        depends_on: 
            - "db"
        command: ["./wait-for-postgres.sh", "db", "python3", "adminbot.py"]
    db:
        image: postgres
        restart: always
        volumes:
            - ./db/dbInitScripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD
            - POSTGRED_DB
    dbadmin:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    postgres_data:
        driver: local