version: '3'
services: 
    bot:
        build: OvivahtiBot
        ports:
            - "22:22"
        volumes:
            - /OvivahtiBot:/bot
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: linnanvahti
            POSTGRES_DB: ovivahtidb
    dbadmin:
        image: adminer
        restart: always
        volumes:
            - /OvivahtiDB:/var/lib/postgresql/data
        ports:
            - 8080:8080
