version: '3'
services: 
    bot:
        build: 
            context: .
            dockerfile: bot/Dockerfile
        ports:
            - "22:22"
        volumes:
            - ./bot:/code/bot
            - ./botlib:/code/bot/botlib
        environment:
            - BOT_TOKEN
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_HOST
        depends_on: 
            - "db"
        command: ["./wait-for-postgres.sh", "db", "python3", "bot/bot.py"]
    adminbot:
        build: 
            context: .
            dockerfile: adminbot/Dockerfile
        ports:
            - "23:22"
        volumes:
            - ./adminbot:/code/adminbot
            - ./botlib:/code/adminbot/botlib
        environment:
            - ADMINBOT_TOKEN
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_HOST
            - USER_BOT_NAME
        depends_on: 
            - "db"
        command: ["./wait-for-postgres.sh", "db", "python3", "adminbot/adminbot.py"]
    db:
        image: postgres
        restart: always
        volumes:
            - ./db/dbInitScripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD
            - POSTGRED_DB
    dbadmin:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    qr:
        image: samwierema/go-qr-generator


volumes:
    postgres_data:
        driver: local