version: '3'
services: 
    bot:
        build: 
            context: .
            dockerfile: bot/Dockerfile
        ports:
            - "22:22"
        volumes:
            - ./bot:/bot
        environment:
            - BOT_TOKEN
    adminbot:
        build: 
            context: .
            dockerfile: adminbot/Dockerfile
        ports:
            - "23:22"
        volumes:
            - ./adminbot:/adminbot
        environment:
            - ADMINBOT_TOKEN
    db:
        image: postgres
        restart: always
        volumes:
            - ./db/dbInitScripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: linnanvahti
            POSTGRED_DB: ovivahtidatabase
    dbadmin:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    pgdata:
        driver: local
